version: 2
jobs:
  build:
    # Setup docker
    docker:
      - image: usdotfhwastol/carma-base:carma-system-3.6.0
        user: carma
        environment:
          TERM: xterm # use xterm to get full display output from build
          INIT_ENV: /home/carma/.base-image/init-env.sh
    working_directory: "/opt/carma/"
    # Execution steps
    steps:
      - run:
          name: Create src folder
          command: |
            mkdir src
            cd src
            mkdir CARMAMsgs
      - checkout:
          path: src/CARMAMsgs
      - run:
          name: Build Package
          command: |
            source ${INIT_ENV}
            export ROS_PARALLEL_JOBS='-j1 -l1' # Try to reduce memory consumption on build
            catkin_make install
      - run:
          name: Run C++ Tests
          command: |
            source ${INIT_ENV}
            source /opt/carma/devel/setup.bash
            export ROS_PARALLEL_JOBS='-j1 -l1' # Try to reduce memory consumption on build
            catkin_make run_tests
