version: 2
jobs:
  build:
    # Setup docker
    docker:
      - image: usdotfhwastol/carma-base:carma-system-4.2.0
        user: carma
        environment:
          TERM: xterm # use xterm to get full display output from build
          INIT_ENV: /home/carma/.base-image/init-env.sh
    working_directory: "/opt/carma/"
    # Execution steps
    steps:
      - run:
          name: Create src folder
          command: |
            mkdir src
            cd src
            mkdir CARMAMsgs
      - checkout:
          path: src/CARMAMsgs
      - run:
          name: Build Packages for ROS1
          command: |
            source ${INIT_ENV}
            export ROS_PARALLEL_JOBS='-j1 -l1' # Try to reduce memory consumption on build
            colcon build --install-base install_ros1 --build-base build_ros1
      - run:
          name: Build Packages for ROS2
          command: |
            source /opt/ros/foxy/setup.bash
            colcon build --parallel-workers 2 # Try to reduce memory consumption on build
